security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'DC=ucm,DC=ltu,DC=sld,DC=cu'
                search_dn: 'CN=reportes,CN=Users,DC=ucm,DC=ltu,DC=sld,DC=cu'
                search_password: 'Aa123456.*'
                default_roles: ROLE_USER
                uid_key: sAMAccountName
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        
        chain_provider:
            chain:
                providers: [ 'app_user_provider', 'my_ldap' ]
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: chain_provider
            
            form_login:
                login_path: app_login
                check_path: app_login

            form_login_ldap:
                login_path: app_login
                check_path: app_login
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'DC=ucm,DC=ltu,DC=sld,DC=cu'
                query_string: '(sAMAccountName={username})'
            #    query_string: '(&(uid={username})(memberOf=CN=INTERNET,OU=OU_GRUPOS,DC=ucm,DC=ltu,DC=sld,DC=cu))'
                search_dn: 'CN=reportes,CN=Users,DC=ucm,DC=ltu,DC=sld,DC=cu'
                search_password: 'Aa123456.*'
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
            logout:
                path: app_logout
                target: app_login

    access_control:
        # ROLE_USER -> usuario Gral | ROLE_ADMIN -> Administrador | ROLE_TEC -> perfil tecnico
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN, ROLE_TEC] }