<?php

namespace ContainerBA6cjLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LNQZWxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L_NQZWx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L_NQZWx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reader' => ['privates', 'DH\\Auditor\\Provider\\Doctrine\\Persistence\\Reader\\Reader', 'getReaderService', true],
        ], [
            'reader' => 'DH\\Auditor\\Provider\\Doctrine\\Persistence\\Reader\\Reader',
        ]);
    }
}
