<?php

namespace ContainerBA6cjLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLdapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Symfony\Component\Ldap\Ldap' shared autowired service.
     *
     * @return \Symfony\Component\Ldap\Ldap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ldap/LdapInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ldap/Ldap.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ldap/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ldap/Adapter/ExtLdap/Adapter.php';

        return $container->privates['Symfony\\Component\\Ldap\\Ldap'] = new \Symfony\Component\Ldap\Ldap(new \Symfony\Component\Ldap\Adapter\ExtLdap\Adapter(['host' => '192.168.1.3', 'port' => 389, 'options' => ['protocol_version' => 3, 'referrals' => false]]));
    }
}
