<?php

namespace ContainerBA6cjLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'DH\Auditor\Provider\Doctrine\Persistence\Reader\Reader' shared service.
     *
     * @return \DH\Auditor\Provider\Doctrine\Persistence\Reader\Reader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/damienharper/auditor/src/Provider/Doctrine/Persistence/Reader/Reader.php';

        return $container->privates['DH\\Auditor\\Provider\\Doctrine\\Persistence\\Reader\\Reader'] = new \DH\Auditor\Provider\Doctrine\Persistence\Reader\Reader(($container->privates['DH\\Auditor\\Provider\\Doctrine\\DoctrineProvider'] ?? $container->getDoctrineProviderService()));
    }
}
