<?php

namespace ContainerBA6cjLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_MyLdapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.user.provider.concrete.my_ldap' shared service.
     *
     * @return \Symfony\Component\Ldap\Security\LdapUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/PasswordUpgraderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ldap/Security/LdapUserProvider.php';

        return $container->privates['security.user.provider.concrete.my_ldap'] = new \Symfony\Component\Ldap\Security\LdapUserProvider(($container->privates['Symfony\\Component\\Ldap\\Ldap'] ?? $container->load('getLdapService')), 'DC=ucm,DC=ltu,DC=sld,DC=cu', 'CN=reportes,CN=Users,DC=ucm,DC=ltu,DC=sld,DC=cu', 'Aa123456.*', [0 => 'ROLE_USER'], 'sAMAccountName', '({uid_key}={username})', NULL, []);
    }
}
