<?php

namespace ContainerBA6cjLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateSchemaCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'DH\Auditor\Provider\Doctrine\Persistence\Command\UpdateSchemaCommand' shared service.
     *
     * @return \DH\Auditor\Provider\Doctrine\Persistence\Command\UpdateSchemaCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LockableTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/damienharper/auditor/src/Provider/Doctrine/Persistence/Command/UpdateSchemaCommand.php';

        $container->privates['DH\\Auditor\\Provider\\Doctrine\\Persistence\\Command\\UpdateSchemaCommand'] = $instance = new \DH\Auditor\Provider\Doctrine\Persistence\Command\UpdateSchemaCommand();

        $instance->setAuditor(($container->privates['DH\\Auditor\\Auditor'] ?? $container->getAuditorService()));
        $instance->setName('audit:schema:update');

        return $instance;
    }
}
