<?php

namespace ContainerBA6cjLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'DH\AuditorBundle\Controller\ViewerController' shared service.
     *
     * @return \DH\AuditorBundle\Controller\ViewerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/damienharper/auditor-bundle/src/Controller/ViewerController.php';

        $container->services['DH\\AuditorBundle\\Controller\\ViewerController'] = $instance = new \DH\AuditorBundle\Controller\ViewerController();

        $instance->setContainer($container);

        return $instance;
    }
}
