<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBA6cjLx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBA6cjLx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBA6cjLx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBA6cjLx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBA6cjLx\App_KernelDevDebugContainer([
    'container.build_hash' => 'BA6cjLx',
    'container.build_id' => 'e05fd41f',
    'container.build_time' => 1625850594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBA6cjLx');
